### PR TITLE
Add Context to RBAC

### PR DESCRIPTION
**Pull request by timo-md**
The actual code changes in this PR are trivial, simply adding context to all relevant calls to enable ABAC functionality while injecting context in an ideomatic way.

I'm contemplating to simply pull this into our rbac package (or make it a subpackage thereof).

Would be interested in hearing your opinions on wich approach you'd consider most beneficial:
- keep as inhoused dependency (separate repo, managed via dep)
- inhoused package in main repo (`pkg/rbac/gorbac` or similar)
- included in current rbac package (all files added to `pkg/rbac`)

my personal tendency is towards option 2.

### CODE REVIEW

**Comment by hwsoderlund** [comment]
I have no opinions on the addition of the context. And I would prefer you move this into pkg/, I see no reason to keep it as a separate repo, it only complicates things. Also, I think it would be best to incorporate our current rbac package and this one into one, if at all possible. Having two would be weird.

**Comment by hwsoderlund** [comment]
So basically my preference is option 3

**Comment by timo-md** [comment]
1. The package hasn't had ANY activity in the last year. All changes within the last 1.5 years have been documentation / bug fixes, so it's stale (if not dead).

2. The changes we introduce change function signatures which implies breaking running code. Which would warrant a major version bump (at the very least).

3. We have now merged the whole gorbac package into our `pkg/rbac` so we can custom tailor it to our needs when necessary.

**Comment by flaviamissi** [comment]
I see. I suppose we wouldn't want to take in the maintenance of that repository?
I'm always leaning to leaving projects open source, we get people improving and reviewing our code for free. But if I'm alone in this then let's just drop it, don't wanna end up having to deal with a possible community by myself.

**Pull request merged**
